/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Aug 31 2026
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>

void ADC_init()
{
   // Configure AN pins and voltage references
    PCFG3 = 0;
    PCFG2 = 0;
    PCFG1 = 0;
    PCFG0 = 0;

    // Right justify ADC result
    ADFM = 1;

    // ADC clock selection
    ADCS2 = 0;
    ADCS1 = 0;
    ADCS0 = 0;

    // Turn ADC on
    ADON = 1;
   }
   

unsigned int ADC_Read(unsigned char channel)
{
    // Select ADC channel
    ADCON0 = (ADCON0 & 0xC7) | ((channel & 0x07) << 3);

    // Acquisition time
    __delay_us(24);

    // Start conversion
    GODONE = 1;

    // Wait for conversion to finish
    while (GODONE);

    // Return 10-bit result
    return ((unsigned int)ADRESH << 8) | ADRESL;
}


void main(void)
 {
PORTD = 0x00;
TRISD = 0x00;
unsigned int adc_value;
unsigned char digit;
unsigned char lower_digit;
unsigned char upper_digit;

ADC_init();

while(1)
{
    adc_value = ADC_Read(1);

    digit = (adc_value * 36) / 1023;
    lower_digit = digit % 10;
   
    upper_digit = digit / 10;

    PORTD = ((PORTD & 0x00) | (lower_digit & 0x0F)) | ((upper_digit & 0x0F) << 4);
}
 }